QuizMan.WEB/Controllers/HomeController.cs
using System.Linq;
using System.Web.Mvc;
using QuizMan.BLL.Interfaces;

namespace QuizMan.WEB.Controllers
{
    /// <summary>
    /// Represents the home controller
    /// </summary>
    public class HomeController : Controller
    {
        private readonly ITestService _testService;
        private readonly ICategoryService _categoryService;
        private readonly IUserService _userService;

        /// <summary>
        /// Initializes an instance of the home controller
        /// </summary>
        /// <param name="testService">Test service</param>
        /// <param name="categoryService">Category service</param>
        /// <param name="userService">User service</param>
        public HomeController( ITestService testService, ICategoryService categoryService, IUserService userService)
        {
            _testService = testService;
            _categoryService = categoryService;
            _userService = userService;
        }

        /// <summary>
        /// Return main application page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            if (TempData["ViewData"] != null)
                ViewData = (ViewDataDictionary)TempData["ViewData"];
            var model = _testService.GetTopUsers().ToList();
            ViewBag.UserCount = _userService.UsersNumber();
            ViewBag.TestCount = _testService.TestsNumber();
            ViewBag.CategoryCount = _categoryService.CategoriesNumber();
            return View(model);
        }

        /// <summary>
        /// About page
        /// </summary>
        /// <returns></returns>
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            return View();
        }

        /// <summary>
        /// Contact page
        /// </summary>
        /// <returns></returns>
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
    }
}

QuizMan.WEB/Controllers/TestController.cs
using Microsoft.AspNet.Identity;
using PagedList;
using QuizMan.BLL.DataTransferObjects;
using QuizMan.BLL.DataTransferObjects.AnswerModel;
using QuizMan.BLL.Interfaces;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using QuizMan.WEB.Models;
using QuizMan.WEB.Utils;

namespace QuizMan.WEB.Controllers
{
    /// <summary>
    /// Represents the test controller
    /// </summary>
    public class TestController : BaseController
    {
        private readonly ITestService _testService;
        private readonly ICategoryService _categoryService;

        /// <summary>
        /// Initializes an instance of the test controller
        /// </summary>
        /// <param name="loggerService">Logger service</param>
        /// <param name="testService">Test service</param>
        /// <param name="categoryService">Category service</param>
        public TestController(ILoggerService loggerService,ITestService testService, ICategoryService categoryService):base(loggerService)
        {
            _testService = testService;
            _categoryService = categoryService;
        }

        /// <summary>
        /// Returns tests by query and category
        /// </summary>
        /// <param name="query">Search query</param>
        /// <param name="categoryId">Category primary key</param>
        /// <returns></returns>
        public async Task<ActionResult> Index(string query, int? categoryId)
        {
            if (query != null && query.Length > 50)
                ModelState.AddModelError("query", "Search string must be no more than 50 characters.");
            ViewBag.Query = query;
            if (categoryId.HasValue)
            {
                ViewBag.CategoryId = categoryId;
                var category = await _categoryService.GetCategoryByIdAsync(categoryId.Value);
                var model = new TestsViewModel
                {
                    Title = category.Title,
                    Description = category.Description
                };
                return View(model);
            }
            if (ModelState.IsValid) return View();
            TempData["ViewData"] = ViewData;
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Returns tests from database
        /// </summary>
        /// <param name="page">Page number</param>
        /// <param name="query">Search query</param>
        /// <param name="currentFilter"></param>
        /// <param name="categoryId">Category primary key</param>
        /// <returns></returns>
        public ActionResult GetTests(int? page, string query, string currentFilter, int? categoryId)
        {
            if (query != null)
                page = 1;
            else
                query = currentFilter;

            ViewBag.CurrentFilter = query;
            ViewBag.CategoryId = categoryId;

            var model = User.Identity.IsAuthenticated ?
                _testService.GetTestsWithProgress(User.Identity.GetUserId(),categoryId).Where(x => !x.Deprecated && x.IsActive).Reverse() :
                _testService.GetTests(categoryId).Where(x => !x.Deprecated && x.IsActive).Reverse();

            foreach (var test in model.Where(test => test.Description.Length > 100))
                test.Description = test.Description.Substring(0, 100) + "...";

            if (!string.IsNullOrEmpty(query))
            {
                if (query.Length > 50) 
                    ModelState.AddModelError("", "Search string must be no more than 50 characters.");
                else
                    model = model.Where(s => s.Title.CaseInsensitiveContains(query));
            }
               
            var pageSize = 9;
            var pageNumber = (page ?? 1);

            return PartialView("TestsPartial", model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Returns user tests results 
        /// </summary>
        /// <param name="page">Page number</param>
        /// <param name="query">Search query</param>
        /// <param name="currentFilter">Current search filter</param>
        /// <param name="userId">User primary key</param>
        /// <returns></returns>
        public ActionResult GetUserTestResults(int? page, string query, string currentFilter, string userId)
        {
            if (query != null)
                page = 1;
            else
                query = currentFilter;
            ViewBag.CurrentFilter = query;
            ViewBag.UserId = userId;
            var model = _testService.GetTestQuickResultsByUserId(userId);
            if (!string.IsNullOrEmpty(query))
            {
                if (query.Length > 50)
                    ModelState.AddModelError("", "Search string must be no more than 50 characters.");
                else
                    model = model.Where(s => s.Title.CaseInsensitiveContains(query));
            }
            var pageSize = 9;
            var pageNumber = (page ?? 1);
            return PartialView("QuickResultsPartial", model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Returns tests by category
        /// </summary>
        /// <param name="page">Page number</param>
        /// <param name="query">Search query</param>
        /// <param name="currentFilter">Current search filter</param>
        /// <param name="categoryId">Category primary key</param>
        /// <returns></returns>
        public ActionResult GetCategoryTests(int? page, string query, string currentFilter, int categoryId)
        {
            if (query != null)
                page = 1;
            else
                query = currentFilter;
            ViewBag.CurrentFilter = query;
            ViewBag.CategoryId = categoryId;
            var model = _testService.GetTestsByCategoryId(categoryId).Reverse();
            if (!string.IsNullOrEmpty(query))
                model = model.Where(s => s.Title.CaseInsensitiveContains(query));

            var pageSize = 5;
            var pageNumber = (page ?? 1);

            return PartialView("CategoryTestsPartial", model.ToPagedList(pageNumber, pageSize));
        }

        /// <summary>
        /// Return test information
        /// </summary>
        /// <param name="testId">Test primary key</param>
        /// <returns></returns>
        public async Task<ActionResult> TestPreview(int testId)
        {
            var model = User.Identity.IsAuthenticated ?
                await _testService.GetTestByIdWithProgress(testId, User.Identity.GetUserId()) :
                await _testService.GetTestById(testId);
            return View(model);
        }

        /// <summary>
        /// The action of the beginning of the test.  
        /// </summary>
        /// <param name="testId">Test primary key</param>
        /// <returns></returns>
        [Authorize]
        public async Task<ActionResult> StartTest(int testId)
        {
            ViewBag.EndTime = await _testService.RegisterUserToTest(User.Identity.GetUserId(), testId);
            var test = await _testService.GetTestWithDetailsByIdAsync(testId);
            return View(test);
        }

        /// <summary>
        /// The post action of the beginning of the test. 
        /// </summary>
        /// <param name="testAnswersModel">User answer model</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> StartTest(TestAnswersModel testAnswersModel)
        {
            await _testService.AddUserAnswer(testAnswersModel, User.Identity.GetUserId());
            return RedirectToAction("GetQuickResult", new { testId = testAnswersModel.TestId });
        }

        /// <summary>
        /// Returns test quick result
        /// </summary>
        /// <param name="testId">Test primary key</param>
        /// <returns></returns>
        [Authorize]
        public async Task<ActionResult> GetQuickResult(int testId)
        {
            var model = await _testService.GetQuickResult(testId, User.Identity.GetUserId());
            return View(model);
        }

        /// <summary>
        /// Returns detailed test result
        /// </summary>
        /// <param name="userId">User primary key</param>
        /// <param name="testId">Test primary key</param>
        /// <returns></returns>
        [Authorize(Roles = Role.Admin)]
        public async Task<ActionResult> GetDetailedResult(string userId, int testId)
        {
            var model = await _testService.GetDetailedResult(testId, userId);
            return View(model);
        }

        /// <summary>
        /// Action for editing test
        /// </summary>
        /// <param name="testId">Test primary key</param>
        /// <returns></returns>
        [AuthorizeRoles(Role.Admin, Role.Editor)]
        public async Task<ActionResult> EditTest(int testId)
        {
            var model = await _testService.GetTestWithDetailsByIdAsync(testId);
            ViewBag.Categories = new SelectList(_categoryService.GetAllCategoriesWithShortDescription(), "Id", "Title", model.CategoryId);
            return View(model);
        }

        /// <summary>
        /// Post action for editing test 
        /// </summary>
        /// <param name="testModel">Test model</param>
        /// <returns></returns>
        [AuthorizeRoles(Role.Admin, Role.Editor)]
        [HttpPost]
        public async Task<ActionResult> EditTest(TestModel testModel)
        {
            ModelState.Merge(_testService.ValidateTestModel(testModel),"");
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = new SelectList(_categoryService.GetAllCategoriesWithShortDescription(), "Id", "Title", testModel.CategoryId);
                return View(testModel);
            }
            await _testService.AddOrUpdateTest(testModel);
            return RedirectToAction("EditCategory", "Category", new { categoryId = testModel.CategoryId });
        }

QuizMan.WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<h2 class="text-center mt-3">
    This platform is designed to test knowledge in various IT areas.
    Use the search on the home page to find the test of interest and start testing yourself.
    Have a successful passing :)
</h2>

QuizMan.WEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2 class="mt-3">@ViewBag.Title.</h2>

<address>
    Ukraine, Kharkiv
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:ivandem666@gmail.com">ivandem666@gmail.com</a><br />
</address>

QuizMan.WEB/Views/Home/Index.cshtml
@using QuizMan.WEB.Utils
@model List<QuizMan.BLL.DataTransferObjects.TopUserModel>
@{
    ViewBag.Title = "Home Page";
}

<div class="home-cap d-flex align-items-center justify-content-center flex-column">
    <h1 class="display-4">QuizMan</h1>
    @using (Html.BeginForm("Index", "Test", FormMethod.Post, new { @class = "needs-validation w-50", novalidate = "" }))
    {
        @Html.ValidationMessage("query")
        <div class="input-group mb-3">
            <input type="text" name="query" class="form-control" placeholder="Search test..." maxlength="50"/>
            <input type="submit" value="Search" class="btn btn-secondary"/>
        </div>
    }
    @Html.ActionLink("ALL TESTS","Index","Test",null, new {@class = "badge bg-secondary text-decoration-none" })
</div>

<div class="row pl-5 pr-5 pt-2">
    <div class="col-md-9">
        <h2 class="text-center">
            Categories
            @if (User.IsInRole(Role.Admin)||User.IsInRole(Role.Editor))
            {
                <a href=@Url.Action("AddCategory","Category") style="vertical-align: middle; cursor: pointer" data-toggle="tooltip" data-placement="top" title="Add new category">
                    <i class="material-icons" >add_box</i>
                </a>
            }
        </h2>
        <div class="row" id="categories-block">
            @Html.Action("GetCategories","Category")
        </div>
    </div>
    <div class="col-md-3">
        <h2 class="text-center">Top users</h2>
        <div class="row" style="margin-top: 29px;">
            @if (Model.Count > 0)
            {
                for (var i = 0; i < Model.Count; i++)
                {
                    <div class="col-12 mb-3">
                        <div class="card text-center">
                            <div class="card-body">
                                @switch (i)
                                {
                                    case 0:<span class="badge bg-gold text-dark ">GOLD</span>
                                        break;
                                    case 1:<span class="badge bg-silver text-dark">SILVER</span>
                                        break;
                                    case 2:<span class="badge bg-bronze">BRONZE</span>
                                        break;
                                }
                                <h5 class="card-title">@Model[i].Name</h5>
                                <h5 class="card-title">@Model[i].Surname</h5>
                                <p class="card-text">Passed Tests: @Model[i].TestPassed</p>
                            </div>
                            <div class="card-footer text-muted">
                                @Html.ActionLink("PROFILE", "Detail", "Account", new { userId = Model[i].Id }, new { @class = "card-link" })
                            </div>
                        </div>
                    </div>
                }
            }
            else
            {
                <h3 class="text-center">
                    It's empty here. Be the first.
                </h3>
            }
        </div>
    </div>
</div>

<div class="row home-footer">
    <div class="stat-footer">
        Categories: @ViewBag.CategoryCount
    </div>
    <div class="stat-footer">
        Tests: @ViewBag.TestCount
    </div>
    <div class="stat-footer">
        Users: @ViewBag.UserCount
    </div>
</div>
<script>
</script>